name: build_installer
run-name: Building the installer...

on: [workflow_dispatch]

jobs:
  build:
    name: Building the installer...
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pyinstaller
      - run: |
          cd installer
          pip install -r requirements.txt pyinstaller
          pyinstaller pissmc-installer.spec
          ls